### ISSUE TITLE
Bug: ButtonPanelOffOn

### ISSUE THREAD

**Issue by mcmicha** [H-J-P/Ikarus#1]
Moin Heinz,

der [toyojoe](https://forums.eagle.ru/showpost.php?p=2932760&postcount=45) hat einen Bug beim ButtonPanelOffOn festgestellt.
Es betrifft die Funktionalität beim benutzen mit einem Touchscreen.

Klickt man den Button per Touch-Eingabe an, wird das Panel angezeigt,. Läst man den Button los, wird das Panel wieder ausgeblendet.

Mit der Maus funktioniert wie es soll.

CU Micha

**Comment by H-J-P** [comment]
mmhhh, sehr merkwürdig. Denn die Function ist die gleiche wie beim MouseDown Event:

```
    private void UpperRec_MouseDown(object sender, MouseButtonEventArgs e)
    {
        if (SwitchUp.Visibility == System.Windows.Visibility.Visible)
        {
            SetValue(0.0);
        }
        else
        {
            SetValue(1.0);
        }
    }

    private void UpperRec_TouchDown(object sender, TouchEventArgs e)
    {
        if (SwitchUp.Visibility == System.Windows.Visibility.Visible)
        {
            SetValue(0.0);
        }
        else
        {
            SetValue(1.0);
        }
    }
```

**Comment by H-J-P** [comment]
Es sei denn, dass TouchDown Event wird 2 mal ausgeführt. Das dürfte aber nicht passieren.

**Comment by H-J-P** [comment]
Leider kann ich das hier nicht testen. Beim SwitchPanelOffOn wird es dieses Problem nicht geben. Vielleicht solltest Du besser diese Klasse dafür einsetzen. Da ist es egal, ob ein Event mehrfach kommt.

**Comment by H-J-P** [comment]
Ich verriegle jetzt das TouchDown Event, nach dem 1. Event. Durch das TouchUp Event, wird das TouchDown event wieder freigegeben.

```
    private void UpperRec_TouchDown(object sender, TouchEventArgs e)
    {
        if (!touchDown)
        {
            touchDown = true;

            if (SwitchUp.Visibility == System.Windows.Visibility.Visible)
            {
                SetValue(0.0);
            }
            else
            {
                SetValue(1.0);
            }
        }
    }

    private void UpperRec_TouchUp(object sender, TouchEventArgs e)
    {
        touchDown = false;
    }
```

Probiere das bitte einmal mit der nächsten Version aus.

**Comment by H-J-P** [comment]
Upload Version 0.9917

**Comment by H-J-P** [comment]
```
public partial class ButtonPanelOffOn : UserControl, I_Ikarus
{
    private bool touchDown = false;
    ....
}
```

Somit kann touchDown nur durch die beiden obigen Funktionen für eine Instanz dieses Buttons geändert werden.

**Comment by H-J-P** [comment]
Die Bedienung per Touch - Event funktioniert jetzt deutlich besser

**Comment by H-J-P** [comment]
Die Bedienung per Touch - Event funktioniert jetzt.
