### ISSUE TITLE
Panels showing behind front panel

### ISSUE THREAD

**Issue by DrSilfver** [H-J-P/Ikarus#5]
Hi, thanks for your efforts put into Ikarus. I'm really excited about this software, great work!. I'm a new user to Ikarus and immediately came upon a problem when trying to use it on my touch screen. Hopefully, its an easy fix? The problem is a strange one and it appears as follows. I'm using Ikarus 1.2.2.0c, the A-10C profile and a 1920x1080 touch screen as the lower half of my windows desktop (1920x2160). In the configuration tab of Ikarus I added 1080 to the Pos. Y values in order to display the A-10 instruments on the touch screen - it worked fine. Using the mouse to press any switch to display any of the panels 2-8 (e.g. Elec. Panel) also works fine. But when I use my finger to flip the same switch the panel is once again opened BUT it is displayed behind the front panel and therefore impossible to use! Strange I admit. My only idea, at this point, is that a mouse click event and a touch event is different and that somehow the window on top doesn't work as it should. What do you think?

**Comment by H-J-P** [comment]
Hi,

thanks for your report. Strange. I have a look at it. Thank you.

---

_CU Heinz_

PS: ... die 1000 Kleinigkeiten ... und halte es einfach (keep it simple)
... 

Am 05.01.2018 20:53 schrieb DrSilfver: 

> Hi, thanks for your efforts put into Ikarus. I'm really excited about this software, great work!. I'm a new user to Ikarus and immediately came upon a problem when trying to use it on my touch screen. Hopefully, its an easy fix? The problem is a strange one and it appears as follows. I'm using Ikarus 1.2.2.0c, the A-10C profile and a 1920x1080 touch screen as the lower half of my windows desktop (1920x2160). In the configuration tab of Ikarus I added 1080 to the Pos. Y values in order to display the A-10 instruments on the touch screen - it worked fine. Using the mouse to press any switch to display any of the panels 2-8 (e.g. Elec. Panel) also works fine. But when I use my finger to flip the same switch the panel is once again opened BUT it is displayed behind the front panel and therefore impossible to use! Strange I admit. My only idea, at this point, is that a mouse click event and a touch event is different and that somehow the window on top doesn't work as it should. What do
you think? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/H-J-P/Ikarus/issues/5
[2]
