### ISSUE TITLE
Run on ARM

### ISSUE THREAD

**Issue by HellSpawn754** [H-J-P/Ikarus#9]
Hallo! 
Vielen Dank für das Projekt. Es funktioniert am PC einwandfrei. 
Ich wollte fragen, ob es möglich ist es für ARM zu kompilieren. Um es zum Beispiel auf einem Raspberry Pi laufen zu lassen. 

lg Herbert

**Comment by H-J-P** [comment]
Hallo Herbert,


das könnte zukünftig funktionieren mit .Net Core 3.0.

Schaue mal hier:

https://www.hackster.io/Ra5tko/running-native-net-core-apps-on-raspberry-pi-arm-0bb717

Vielleicht probierst Du es mal selbst. ;-)


CU Heinz

PS: ... die 1000 Kleinigkeiten ... und halte es einfach (keep it simple) ...

**Comment by HellSpawn754** [comment]
Das könnte funktionieren. Ich werde es testen. Tausend Dank!

lg Herbert
